"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { Magnetic } from "./MotionText";

const links=[{label:"About",href:"/about"},{label:"Work",href:"/work"},{label:"Contact",href:"/#contact"}];

export default function Navbar(){
  const pathname=usePathname();const reduced=useReducedMotion();const [collapsed,setCollapsed]=useState(false);const [open,setOpen]=useState(false);const lastY=useRef(0);const ticking=useRef(false);
  // Hash links (e.g. "/#contact") only trigger a scroll on a pathname change (see SmoothScroll.jsx), so clicking
  // one while already on that page does nothing by default — scroll to the target ourselves in that case.
  const goToHash=(event,href)=>{if(!href.startsWith("/#")||pathname!=="/")return;event.preventDefault();document.getElementById(href.slice(2))?.scrollIntoView({behavior:reduced?"auto":"smooth",block:"start"});window.history.replaceState(null,"",href);};
  useEffect(()=>{lastY.current=window.scrollY;const onScroll=()=>{if(ticking.current)return;ticking.current=true;requestAnimationFrame(()=>{const current=window.scrollY;const delta=current-lastY.current;if(current<70||delta< -8){setCollapsed(false);setOpen(false)}else if(delta>8)setCollapsed(true);lastY.current=current;ticking.current=false})};window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
  useEffect(()=>{if(!open)return;const previous=document.activeElement;document.body.style.overflow="hidden";const escape=e=>e.key==="Escape"&&setOpen(false);window.addEventListener("keydown",escape);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",escape);previous?.focus?.()}},[open]);
  return <header className="pointer-events-none fixed inset-x-0 top-0 z-50 px-4 py-4 md:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3">
    <motion.div layout className="pointer-events-auto"><Link href="/#home" onClick={(event)=>{if(pathname==="/"){event.preventDefault();document.getElementById("home")?.scrollIntoView({behavior:reduced?"auto":"smooth",block:"start"});window.history.replaceState(null,"","/");}}} aria-label="Go to homepage" className="inline-flex min-h-11 items-center text-xs font-bold uppercase tracking-[.22em] text-hud-text transition hover:text-gold focus-visible:text-gold">Vansh Bajaj<span className="text-gold">®</span></Link></motion.div>
    <div className="pointer-events-auto ml-auto flex items-center gap-3"><AnimatePresence mode="wait" initial={false}>{!collapsed?<motion.nav key="links" aria-label="Primary navigation" className="flex items-center gap-2 sm:gap-5" initial={reduced?false:{opacity:0,y:-12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:.28}}>{links.map(link=><Link key={link.label} href={link.href} onClick={(event)=>goToHash(event,link.href)} aria-current={pathname===link.href?"page":undefined} className="whitespace-nowrap text-[9px] font-semibold uppercase tracking-[.08em] text-hud-muted transition hover:text-gold sm:text-[11px] sm:tracking-[.12em] md:text-xs"><Magnetic strength={.14}>{link.label}</Magnetic></Link>)}</motion.nav>:<motion.button key="menu" type="button" aria-expanded={open} aria-controls="collapsed-menu" aria-label={open?"Close menu":"Open menu"} onClick={()=>setOpen(value=>!value)} className="grid h-12 w-12 place-items-center rounded-full bg-cosmic/80 text-hud-text backdrop-blur-xl transition hover:text-gold" initial={reduced?false:{opacity:0,scale:.75,rotate:-35}} animate={{opacity:1,scale:1,rotate:0}} exit={{opacity:0,scale:.75,rotate:35}}><span aria-hidden="true" className="text-xl leading-none">{open?"×":"≡"}</span></motion.button>}</AnimatePresence></div>
  </div><AnimatePresence>{open&&<><motion.button type="button" aria-label="Close navigation" onClick={()=>setOpen(false)} className="pointer-events-auto fixed inset-0 z-[51] bg-black/45 backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.nav id="collapsed-menu" aria-label="Collapsed navigation" className="pointer-events-auto fixed right-4 top-20 z-[52] flex w-[min(22rem,calc(100vw-2rem))] flex-col rounded-3xl bg-cosmic p-6 shadow-2xl" initial={reduced?{opacity:0}:{opacity:0,y:-18,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-12,scale:.97}} transition={{duration:.35,ease:[.16,1,.3,1]}}>{links.map((link,index)=><motion.div key={link.label} initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:.05+index*.04}}><Link href={link.href} onClick={(event)=>{setOpen(false);goToHash(event,link.href);}} className="block border-b border-white/10 py-4 text-2xl font-medium uppercase text-hud-text transition hover:pl-2 hover:text-gold">{link.label}</Link></motion.div>)}</motion.nav></>}</AnimatePresence></header>;
}
